"""Add completed Tasks model

Revision ID: 1325de28ab15
Revises: 4897ed6c465d
Create Date: 2026-05-23 15:22:28.436282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1325de28ab15'
down_revision: Union[str, Sequence[str], None] = '4897ed6c465d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('completed', sa.Boolean(), nullable=False, server_default="false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Tasks', 'completed')
    # ### end Alembic commands ###
