"""Add task id in product

Revision ID: 2814f86a51cf
Revises: 5f4678379ebd
Create Date: 2026-05-19 10:38:24.551798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2814f86a51cf'
down_revision: Union[str, Sequence[str], None] = '5f4678379ebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Products', 'create_data',
               existing_type=sa.INTEGER(),
               type_=sa.BigInteger(),
               existing_nullable=False)
    op.alter_column('Tasks', 'interval',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Tasks', 'interval',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Products', 'create_data',
               existing_type=sa.BigInteger(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
