"""Rebuild task model

Revision ID: 2d3f240f42be
Revises: 4ef8765bb5fb
Create Date: 2026-05-11 18:05:35.229108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d3f240f42be'
down_revision: Union[str, Sequence[str], None] = '4ef8765bb5fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tasks_mode'), table_name='Tasks')
    op.drop_column('Tasks', 'mode')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('mode', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_Tasks_mode'), 'Tasks', ['mode'], unique=False)
    # ### end Alembic commands ###
