"""Delete field in Tasks model

Revision ID: 4897ed6c465d
Revises: 0855d87550a4
Create Date: 2026-05-21 19:49:03.510493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4897ed6c465d'
down_revision: Union[str, Sequence[str], None] = '0855d87550a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tasks_last_views'), table_name='Tasks')
    op.drop_column('Tasks', 'last_views')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('last_views', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index(op.f('ix_Tasks_last_views'), 'Tasks', ['last_views'], unique=False)
    # ### end Alembic commands ###
