"""Rebuild Products

Revision ID: 4ceac643eb78
Revises: 54cf3a2cc3ae
Create Date: 2026-05-19 21:01:41.529121

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ceac643eb78'
down_revision: Union[str, Sequence[str], None] = '54cf3a2cc3ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Products', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Products', 'price',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Products', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('Products', 'url_photo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Products', 'url_photo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Products', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Products', 'price',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Products', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('Products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
