"""Add last_update in tasks

Revision ID: 4ef8765bb5fb
Revises: 
Create Date: 2026-05-08 10:29:45.975583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ef8765bb5fb'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Tasks', sa.Column('last_update', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_Tasks_id'), 'Tasks', ['id'], unique=False)
    op.create_index(op.f('ix_Tasks_interval'), 'Tasks', ['interval'], unique=False)
    op.create_index(op.f('ix_Tasks_last_views'), 'Tasks', ['last_views'], unique=False)
    op.create_index(op.f('ix_Tasks_launches'), 'Tasks', ['launches'], unique=False)
    op.create_index(op.f('ix_Tasks_mode'), 'Tasks', ['mode'], unique=False)
    op.create_index(op.f('ix_Tasks_scheduled_at'), 'Tasks', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_Tasks_url'), 'Tasks', ['url'], unique=False)
    op.create_index(op.f('ix_Tasks_user_id'), 'Tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_Tasks_user_id'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_url'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_scheduled_at'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_mode'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_launches'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_last_views'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_interval'), table_name='Tasks')
    op.drop_index(op.f('ix_Tasks_id'), table_name='Tasks')
    op.drop_column('Tasks', 'last_update')
    # ### end Alembic commands ###
