"""Dev

Revision ID: 544fdf8795cf
Revises: 1325de28ab15
Create Date: 2026-05-25 17:17:23.985659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '544fdf8795cf'
down_revision: Union[str, Sequence[str], None] = '1325de28ab15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('create_date', sa.BigInteger(), nullable=False))
    op.drop_column('Products', 'create_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Products', sa.Column('create_data', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('Products', 'create_date')
    # ### end Alembic commands ###
